# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mixmod <- function(lhm, penalty_coef = 0.) {
    .Call(`_exprest_mixmod`, lhm, penalty_coef)
}

